const sections = [
  {
    id: 1,
    category: "burialtype",
    instruction: "Wähle eine Art der Beisetzung",
    multiplechoice: 0,
    setofchoices: [
      {
        id: 0,
        img: "https://cdn.pixabay.com/photo/2019/04/04/11/23/cemetery-4102571_960_720.jpg",
        body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur aliquet lacus nibh, id molestie lorem cursus id. In erat nibh, consequat ultrices sem a, posuere imperdiet justo. In varius eu nisi eu fringilla. Fusce vitae lorem aliquet, fringilla ipsum id, rhoncus magna. Pellentesque velit magna, dictum eu tempus volutpat, gravida vel justo. Suspendisse ut neque eu felis hendrerit malesuada. Morbi porta fermentum feugiat. Maecenas a facilisis velit, non ultrices dui. Maecenas lacus tortor, fermentum quis metus rhoncus, ultricies interdum dui. Proin nunc nulla, auctor vel arcu ut, semper mattis nisl. Aenean in mi metus. Phasellus scelerisque eget quam eu sodales. Integer ac velit luctus, sollicitudin neque quis, finibus nisi. ",
        title: "Friedhof mit Urne",
        process: "",
        cost: 1400,
      },
      {
        id: 1,
        img: "https://cdn.pixabay.com/photo/2019/04/04/11/23/cemetery-4102571_960_720.jpg",
        body: "",
        title: "Friedhof mit Sarg",
        process: "",
        cost: 1900,
      },
      {
        id: 2,
        img: "https://cdn.pixabay.com/photo/2019/04/04/11/23/cemetery-4102571_960_720.jpg",
        body: "",
        title:
          "Friedhof mit Reerdigung (neues beschleunigtes Kompostierverfahren)",
        process: "",
        cost: 2100,
      },
      {
        id: 3,
        img: "https://cdn.pixabay.com/photo/2019/04/04/11/23/cemetery-4102571_960_720.jpg",
        body: "",
        title: "Nicht auf einem Friedhof (z.B. See, Wald, Feld)",
        process: "",
        cost: 1300,
      },
    ],
  },
  {
    id: 2,
    category: "sizeofevent",
    instruction: "Mit wie vielen Teilnehmenden planst du?",
    multiplechoice: 0,
    setofchoices: [
      {
        id: 0,
        img: "https://cdn.pixabay.com/photo/2020/05/25/13/15/golden-weddings-5218598_960_720.jpg",
        body: "",
        title: "Kleiner Kreis (max. 10 Teilnehmende)",
        process: "",
        cost: 300,
      },
      {
        id: 1,
        img: "https://cdn.pixabay.com/photo/2020/05/25/13/15/golden-weddings-5218598_960_720.jpg",
        body: "",
        title: "Mittlere Größe (10 - 30 Teilnehmende)",
        process: "",
        cost: 400,
      },
      {
        id: 2,
        img: "https://cdn.pixabay.com/photo/2020/05/25/13/15/golden-weddings-5218598_960_720.jpg",
        body: "",
        title: "Große Veranstaltung (30+ Teilnehmende)",
        process: "",
        cost: 600,
      },
    ],
  },
  {
    id: 3,
    category: "add-ons",
    instruction: "Wähle weitere Elemente aus",
    multiplechoice: 1,
    setofchoices: [
      {
        id: 0,
        img: "https://cdn.pixabay.com/photo/2016/11/26/09/23/funeral-1860298_960_720.jpg",
        body: "",
        title: "Trauerredner:in",
        process: "",
        cost: 350,
      },
      {
        id: 1,
        img: "https://cdn.pixabay.com/photo/2016/11/26/09/23/funeral-1860298_960_720.jpg",
        body: "",
        title: "Musiker:in",
        process: "",
        cost: 150,
      },
      {
        id: 2,
        img: "https://cdn.pixabay.com/photo/2016/11/26/09/23/funeral-1860298_960_720.jpg",
        body: "",
        title: "Blumen",
        process: "",
        cost: 200,
      },
      {
        id: 3,
        img: "https://cdn.pixabay.com/photo/2016/11/26/09/23/funeral-1860298_960_720.jpg",
        body: "",
        title: "Anzeige in einer lokalen Zeitung",
        process: "",
        cost: 50,
      },
      {
        id: 4,
        img: "https://cdn.pixabay.com/photo/2016/11/26/09/23/funeral-1860298_960_720.jpg",
        body: "",
        title: "Grabstein",
        process: "",
        cost: 450,
      },
    ],
  },
];
export default sections;
