const sections = [
  {
    id: 1,
    category: "burialtype",
    instruction: "Wähle eine Art der Beisetzung",
    multiplechoice: 0,
    setofchoices: [
      {
        id: 0,
        img: "",
        body: "",
        title: "Friedhof mit Urne",
        process: "",
        cost: 1400,
      },
      {
        id: 1,
        img: "",
        body: "",
        title: "Friedhof mit Sarg",
        process: "",
        cost: 1900,
      },
      {
        id: 2,
        img: "",
        body: "",
        title:
          "Friedhof mit Reerdigung (neues beschleunigtes Kompostierverfahren)",
        process: "",
        cost: 2100,
      },
      {
        id: 3,
        img: "",
        body: "",
        title: "Nicht auf einem Friedhof (z.B. See, Wald, Feld)",
        process: "",
        cost: 1300,
      },
    ],
  },
  {
    id: 2,
    category: "sizeofevent",
    instruction: "Mit wie vielen Teilnehmenden planst du?",
    multiplechoice: 0,
    setofchoices: [
      {
        id: 0,
        img: "",
        body: "",
        title: "Kleiner Kreis (max. 10 Teilnehmende)",
        process: "",
        cost: 300,
      },
      {
        id: 1,
        img: "",
        body: "",
        title: "Mittlere Größe (10 - 30 Teilnehmende)",
        process: "",
        cost: 400,
      },
      {
        id: 2,
        img: "",
        body: "",
        title: "Große Veranstaltung (30+ Teilnehmende)",
        process: "",
        cost: 600,
      },
    ],
  },
  {
    id: 3,
    category: "add-ons",
    instruction: "Wähle weitere Elemente aus",
    multiplechoice: 1,
    setofchoices: [
      {
        id: 0,
        img: "",
        body: "",
        title: "Trauerredner:in",
        process: "",
        cost: 350,
      },
      {
        id: 1,
        img: "",
        body: "",
        title: "Musiker:in",
        process: "",
        cost: 150,
      },
      {
        id: 2,
        img: "",
        body: "",
        title: "Blumen",
        process: "",
        cost: 200,
      },
      {
        id: 3,
        img: "",
        body: "",
        title: "Anzeige in einer lokalen Zeitung",
        process: "",
        cost: 50,
      },
      {
        id: 4,
        img: "",
        body: "",
        title: "Grabstein",
        process: "",
        cost: 450,
      },
    ],
  },
];
export default sections;
